Issue #172 - Removed 'reserved' characters from the quote_key method
ravendb/RavenDB-Python-Client pull request #173
Opened 2023-03-22 12:21 UTC by poissoncorp

Loading documents with `+` sign in the document id has returned `None` values.
The cause was in the `quote_key`, `+` sign was considered safe, which resulted in an invalid URL.

https://github.com/ravendb/ravendb-python-client/issues/172

2023-03-22 14:14 UTC, ayende requested changes

2023-03-22 14:14 UTC, ayende commented on ravendb/tools/utils.py
> +        reserved = "%:=&?~#!$,;'*[]"
I believe that we should remove all of those.
Why do we have it in the first place?
What if we have a document id with `?`, or a `&` (The later one I can think of a few scenarios for)

2023-03-22 16:02 UTC, poissoncorp commented on ravendb/tools/utils.py
> +        reserved = "%:=&?~#!$,;'*[]"
Force pushed the changes and extended the test.

2023-03-23 09:45 UTC, ayende approved these changes

2023-03-23 10:45 UTC, merged